---
- name: Bootstrap | Check if bootstrap is needed
  raw: stat {{ bin_dir }}/.bootstrapped
  register: need_bootstrap
  failed_when: false
  changed_when: false
  tags:
    - facts

- name: Force binaries directory for Container Linux by CoreOS
  set_fact:
    bin_dir: "{{ bin_dir }}"
  tags:
    - facts

- name: Bootstrap | Run bootstrap.sh
  script: bootstrap.sh
  when: need_bootstrap.rc != 0

- name: Bootstrap | Set ansible_python_interpreter
  set_fact:
    ansible_python_interpreter: "{{ bin_dir }}/python"
  tags:
    - facts

- include_tasks: path.yml
